version: '3.1'

volumes:
  quiz_storage_pg_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/artur/docker-volumes-data/quiz-storage-pg-data
  quiz_storage_keycloak_providers:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/artur/docker-volumes-data/quiz-storage-keycloak-providers

networks:
  local:
    driver: bridge

services:
  quiz_storage_keycloak_pg:
    image: postgres
    volumes:
      - quiz_storage_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: quiz_storage_keycloak_pg
    ports:
      - 5432:5432
    networks:
      - local
  quiz_storage_keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
#    command:
#      - start-dev
    command: ['start-dev']
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://quiz_storage_keycloak_pg/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KEYCLOAK_PASSWORD: admin
    volumes:
      - quiz_storage_keycloak_providers:/opt/keycloak/providers
    ports:
      - 8080:8080
    networks:
      - local
    depends_on:
      - quiz_storage_keycloak_pg